analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    unawaited_futures: error
    todo: ignore
  exclude:
    - flutter/**
    - lib/api/*.dart
    - .dart_tool

linter:
  rules:
    - unawaited_futures
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks

include: package:pedantic/analysis_options.yaml
